DROP TABLE IF EXISTS COMIC_MODEL_AUTORES;
DROP TABLE IF EXISTS COMIC_MODEL_PERSONAGENS;

CREATE TABLE COMIC_AUTORES (
    comic_id BIGINT NOT NULL,
    autor_nome VARCHAR(255) NOT NULL
);

CREATE TABLE COMIC_PERSONAGENS (
    comic_id BIGINT NOT NULL,
    personagem_nome VARCHAR(255) NOT NULL
);
